USE biblioteca_pessoal_1s2026;

select * from livro;

/* 
 CONTA LIVROS LIDOS E NÃO LIDOS
 POR USUÁRIO
 OU
 CONTA REGISTROS AGRUPANDO PELAS COLUNAS
 ID_USUARIO E LIDO
*/
SELECT 
	ID_USUARIO,
    LIDO,
	COUNT(*) AS QTD
FROM 
	LIVRO
GROUP BY
	ID_USUARIO,
    LIDO
;
    
/*
	CALCULA QUANTIDADES, PERCENTUAIS E MAX E MIN
    USANDO FUNÇÕES DE AGREGAÇÃO
*/    
SELECT
	t1.ID_USUARIO,
    t2.NOME,
	COUNT(t1.ID_LIVRO) AS QTD_LIVRO,
    SUM(t1.LIDO) AS QTD_LIVRO_LIDO,
    ROUND((SUM(t1.LIDO) / COUNT(t1.ID_LIVRO))*100, 2) AS PCT_LIDO,
    MAX(t1.ANO_PUBLICACAO) AS ANO_MAIS_RECENTE,
    MIN(t1.ANO_PUBLICACAO) AS ANO_MAIS_ANTIGO
FROM
	LIVRO t1
JOIN 
	USUARIO t2 ON (t1.ID_USUARIO = t2.ID_USUARIO)
GROUP BY
	t1.ID_USUARIO,
    t2.NOME
;

/*
	CALCULA A IDADE DOS AUTORES
*/
SELECT
	NOME,
    ANO_NASCIMENTO,
    ANO_MORTE,
    (IF(ANO_MORTE > 0, ANO_MORTE, YEAR(CURRENT_DATE()))  - ANO_NASCIMENTO) AS IDADE
FROM
	AUTOR;
    
/*
	CALCULA A IDADE MÉDIA DOS AUTORES
*/
SELECT
    AVG(
		IF(ANO_MORTE > 0, ANO_MORTE, YEAR(CURRENT_DATE()))  - ANO_NASCIMENTO
	) AS IDADE_MEDIA_AUTOR
FROM
	AUTOR;
    
