USE biblioteca_pessoal_1s2026;

/* CRIA USUÁRIOS */
CREATE USER "UJOAO"@"%" IDENTIFIED BY "123";
CREATE USER "UPEDRO"@"%" IDENTIFIED BY "123";

/* GARANTE ACESSO DE SELECT E UPDATE*/
GRANT SELECT, UPDATE ON biblioteca_pessoal_1s2026.LIVRO 
TO "UJOAO"@"%";

SELECT * FROM AUDIT_LIVRO;

GRANT SELECT, UPDATE ON biblioteca_pessoal_1s2026.LIVRO 
TO "UPEDRO"@"%";

/* REMOVE ACESSO DE UPDATE */
REVOKE UPDATE ON biblioteca_pessoal_1s2026.LIVRO 
FROM "UJOAO"@"%";

REVOKE UPDATE ON biblioteca_pessoal_1s2026.LIVRO 
FROM "UPEDRO"@"%";
