/* DESCREVE A TABELA */
describe livro;
show tables;

/* ADICIONA UMA COLUNA NOVA À TABELA */
ALTER TABLE livro
ADD COLUMN status_leitura VARCHAR(255);

/*  MODIFICA UMA COLUNA EXISTENTE
	DEFAULT DEFINE UM VALOR PADRÃO PARA O CAMPO
 */
ALTER TABLE livro
MODIFY status_leitura BOOLEAN DEFAULT(0); 

/*  ADICIONA RESTRIÇÃO COM VERIFICAÇÃO DO 
	VALOR INSERIDO, LIMITANDO A 0 OU 1.
*/
ALTER TABLE livro
ADD CONSTRAINT check_status_livro
CHECK (status_leitura IN (0, 1) );

/* REMOVE UMA COLUNA DA TABELA */
ALTER TABLE livro
DROP COLUMN status_leitura;

/*
	ADICIONA UMA COLUNA ID COMO CHAVE ESTRANGEIRA
    E CRIA RESTRIÇÃO DE REFERÊNCIA E DEFINE
    O COMPORTAMENTO DE EXCLUSÃO/DELETE
*/

ALTER TABLE livro
ADD COLUMN id_usuario INT,
ADD CONSTRAINT fk_livro_usuario
FOREIGN KEY (id_usuario)
REFERENCES usuario(id_usuario)
ON DELETE CASCADE;


