USE biblioteca_pessoal_1s2026;

/* Quantidade de livros por categoria */
SELECT
	t2.NOME AS CATEGORIA,
	count(t1.id_livro) AS QTD
FROM
	livro t1
JOIN categoria t2 ON (t1.id_categoria = t2.id_categoria)
GROUP BY t2.NOME;

/* VIEW vw_categoria_livro */
CREATE OR REPLACE VIEW vw_categoria_livro AS (
SELECT
	t2.NOME AS CATEGORIA,
	count(t1.id_livro) AS QTD
FROM
	livro t1
JOIN categoria t2 ON (t1.id_categoria = t2.id_categoria)
GROUP BY t2.NOME
);


/* CONSULTA DADOS DA VIEW*/
SELECT * FROM vw_categoria_livro;

/* VW_LIVRO_LIDO */
CREATE OR REPLACE VIEW VW_LIVRO_LIDO AS (
SELECT TITULO, LIDO FROM LIVRO WHERE LIDO = 1
);

SELECT * FROM VW_LIVRO_LIDO;

/* CRIA VW_RELATÓRIO */
CREATE OR REPLACE VIEW VW_RELATORIO AS (
SELECT
	t2.NOME AS CATEGORIA,
	COUNT(t1.id_livro) AS QTD,
    SUM(t1.LIDO) AS QTD_LIDO,
    ROUND((SUM(t1.LIDO) / COUNT(t1.id_livro))*100, 2) AS PC_LIDO
FROM
	livro t1
JOIN categoria t2 ON (t1.id_categoria = t2.id_categoria)
GROUP BY t2.NOME
);

SELECT * FROM VW_RELATORIO;

/* 
	PARA MELHORAR A PERFORMANCE, VAMOS CRIAR UM STORED PROCEDURE
    QUE CARREGA OS DADOS DA VW_RELATORIO EM UMA TABELA RELATORIO
*/
DELIMITER $$
CREATE PROCEDURE SP_ATUALIZAR_RELATORIO()
BEGIN
	/* INICIA TRANSAÇÃO */
    START TRANSACTION;
    
    /* 1. DELETA TABELA RELATORIO SE EXISTIR */
    DROP TABLE IF EXISTS RELATORIO;
    
    /* 2. CRIA TABELA RELATORIO */
    CREATE TABLE RELATORIO (
		CATEGORIA VARCHAR(255),
        QTD INT,
        QTD_LIDO INT,
        PC_LIDO DECIMAL
    );
    
    /* 3. INSERE DADOS DA VIEW NA TABELA RELATORIO */
    INSERT INTO RELATORIO (SELECT * FROM VW_RELATORIO);
    
    /* CONFIRMA AS ALTERAÇÕES NO BD */
    COMMIT;
END$$

/* CONSULTA DADOS DO RELATORIO */
SELECT * FROM RELATORIO;

/* EXECUTA PROCEDURE SP_ATUALIZAR_RELATORIO*/
CALL SP_ATUALIZAR_RELATORIO();

/* CONSULTA DADOS DO RELATORIO */
SELECT * FROM RELATORIO;

/* ATUALIZA REGISTROS */
UPDATE LIVRO
SET LIDO = 0
WHERE ID_CATEGORIA = 6;

/* EXECUTA PROCEDURE SP_ATUALIZAR_RELATORIO PARA ATUALIZAR RELATÓRIO*/
CALL SP_ATUALIZAR_RELATORIO();

/* CONSULTA DADOS DO RELATORIO (APÓS ATUALIZAÇÃO ) */
SELECT * FROM RELATORIO;
